### ISSUE TITLE
'Bot' object has no attribute 'send_typing'

### ISSUE THREAD

**Issue by thisisjvgrace** [DevDungeon/ChattyCathy#4]
Hi, when I run your bot, i get this error
```
Message: hello
Ignoring exception in on_message
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/discord/client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cathy-1.1.0-py3.5.egg/cathy/cathy.py", line 59, in on_message
    yield from self.discord_client.send_typing(message.channel)
AttributeError: 'Bot' object has no attribute 'send_typing'
Message: how are you?
Ignoring exception in on_message
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/discord/client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cathy-1.1.0-py3.5.egg/cathy/cathy.py", line 59, in on_message
    yield from self.discord_client.send_typing(message.channel)
AttributeError: 'Bot' object has no attribute 'send_typing'
```

is this a bug?

**Comment by thisisjvgrace** [comment]
Ok its solved now, thanks NanoDano.

**Comment by seanjhatch** [comment]
How did you fix this?

**Comment by NanoDano** [comment]
Make sure you are using python <3.7 and discord.py==0.16.12

**Comment by atheeraa** [comment]
can you please tell me how did you solve it? I have a similar problem and can't find out what is wrong with it
